package lib

// Card 结构体
type Card struct {
	Card_id   int    `json:"id"`   // ID 用来唯一标识一张塔罗牌
	Card_name string `json:"name"` // Name 是塔罗牌的名称
	Card_type string `json:"type"` // Type 是塔罗牌的类型
	Card_up   string `json:"up"`   // Up 是正位的含义
	Card_down string `json:"down"` // Down 是逆位的含义
	Card_file string `json:"file"` // File 是塔罗牌对应的文件路径
}

// Cards 是一个包含所有塔罗牌的数组
// 每张塔罗牌都包含 ID、名称、类型、正位含义、逆位含义和文件路径
// 共有 78 张塔罗牌
var Cards [78]Card = [78]Card{{
	Card_id:   0,
	Card_name: "愚者",
	Card_type: "MajorArcana",
	Card_up:   "新的开始、冒险、自信、乐观、好的时机",
	Card_down: "时机不对、鲁莽、轻信、承担风险",
	Card_file: "MajorArcana/00-THE-FOOL"}, {
	Card_id:   1,
	Card_name: "魔术师",
	Card_type: "MajorArcana",
	Card_up:   "创造力、主见、激情、发展潜力",
	Card_down: "缺乏创造力、优柔寡断、才能平庸、计划不周",
	Card_file: "MajorArcana/01-THE-MAGICIAN"}, {
	Card_id:   2,
	Card_name: "女祭司",
	Card_type: "MajorArcana",
	Card_up:   "潜意识、洞察力、知性、研究精神",
	Card_down: "自我封闭、内向、神经质、缺乏理性",
	Card_file: "MajorArcana/02-THE-HIGH-PRIESTESS"}, {
	Card_id:   3,
	Card_name: "女皇",
	Card_type: "MajorArcana",
	Card_up:   "母性、女性特质、生命力、接纳",
	Card_down: "生育问题、不安全感、敏感、困扰于细枝末节",
	Card_file: "MajorArcana/03-THE-EMPRESS"}, {
	Card_id:   4,
	Card_name: "皇帝",
	Card_type: "MajorArcana",
	Card_up:   "控制、意志、领导力、权力、影响力",
	Card_down: "混乱、固执、暴政、管理不善、不务实",
	Card_file: "MajorArcana/04-THE-EMPEROR"}, {
	Card_id:   5,
	Card_name: "教皇",
	Card_type: "MajorArcana",
	Card_up:   "值得信赖的、顺从、遵守规则",
	Card_down: "失去信赖、固步自封、质疑权威、恶意的规劝",
	Card_file: "MajorArcana/05-THE-HIEROPHANT"}, {
	Card_id:   6,
	Card_name: "恋人",
	Card_type: "MajorArcana",
	Card_up:   "爱、肉体的连接、新的关系、美好时光、互相支持",
	Card_down: "纵欲过度、不忠、违背诺言、情感的抉择",
	Card_file: "MajorArcana/06-THE-LOVERS"}, {
	Card_id:   7,
	Card_name: "战车",
	Card_type: "MajorArcana",
	Card_up:   "高效率、把握先机、坚韧、决心、力量、克服障碍",
	Card_down: "失控、挫折、诉诸暴力、冲动",
	Card_file: "MajorArcana/07-THE-CHARIOT"}, {
	Card_id:   8,
	Card_name: "力量",
	Card_type: "MajorArcana",
	Card_up:   "勇气、决断、克服阻碍、胆识过人",
	Card_down: "恐惧、精力不足、自我怀疑、懦弱",
	Card_file: "MajorArcana/08-STRENGTH"}, {
	Card_id:   9,
	Card_name: "隐士",
	Card_type: "MajorArcana",
	Card_up:   "内省、审视自我、探索内心、平静",
	Card_down: "孤独、孤立、过分慎重、逃避",
	Card_file: "MajorArcana/09-THE-HERMIT"}, {
	Card_id:   10,
	Card_name: "命运之轮",
	Card_type: "MajorArcana",
	Card_up:   "把握时机、新的机会、幸运降临、即将迎来改变",
	Card_down: "厄运、时机未到、计划泡汤",
	Card_file: "MajorArcana/10-THE-WHEEL-OF-FORTUNE"}, {
	Card_id:   11,
	Card_name: "正义",
	Card_type: "MajorArcana",
	Card_up:   "公平、正直、诚实、正义、表里如一",
	Card_down: "失衡、偏见、不诚实、表里不一",
	Card_file: "MajorArcana/11-JUSTICE"}, {
	Card_id:   12,
	Card_name: "倒吊人",
	Card_type: "MajorArcana",
	Card_up:   "进退两难、接受考验、因祸得福、舍弃行动追求顿悟",
	Card_down: "无畏的牺牲、利己主义、内心抗拒、缺乏远见",
	Card_file: "MajorArcana/12-THE-HANGED-MAN"}, {
	Card_id:   13,
	Card_name: "死神",
	Card_type: "MajorArcana",
	Card_up:   "失去、舍弃、离别、死亡、新生事物的来临",
	Card_down: "起死回生、回心转意、逃避现实",
	Card_file: "MajorArcana/13-DEATH"}, {
	Card_id:   14,
	Card_name: "节制",
	Card_type: "MajorArcana",
	Card_up:   "平衡、和谐、治愈、节制",
	Card_down: "失衡、失谐、沉溺愉悦、过度放纵",
	Card_file: "MajorArcana/14-TEMPERANCE"}, {
	Card_id:   15,
	Card_name: "恶魔",
	Card_type: "MajorArcana",
	Card_up:   "负面影响、贪婪的欲望、物质主义、固执己见",
	Card_down: "逃离束缚、拒绝诱惑、治愈病痛、直面现实",
	Card_file: "MajorArcana/15-THE-DEVIL"}, {
	Card_id:   16,
	Card_name: "高塔",
	Card_type: "MajorArcana",
	Card_up:   "急剧的转变、突然的动荡、毁灭后的重生、政权更迭",
	Card_down: "悬崖勒马、害怕转变、发生内讧、风暴前的寂静",
	Card_file: "MajorArcana/16-THE-TOWER"}, {
	Card_id:   17,
	Card_name: "星星",
	Card_type: "MajorArcana",
	Card_up:   "希望、前途光明、曙光出现",
	Card_down: "好高骛远、异想天开、事与愿违、失去目标",
	Card_file: "MajorArcana/17-THE-STAR"}, {
	Card_id:   18,
	Card_name: "月亮",
	Card_type: "MajorArcana",
	Card_up:   "虚幻、不安与动摇、迷惘、欺骗",
	Card_down: "状况逐渐好转、疑虑渐消、排解恐惧",
	Card_file: "MajorArcana/18-THE-MOON"}, {
	Card_id:   19,
	Card_name: "太阳",
	Card_type: "MajorArcana",
	Card_up:   "活力充沛、生机、远景明朗、积极",
	Card_down: "意志消沉、情绪低落、无助、消极",
	Card_file: "MajorArcana/19-THE-SUN"}, {
	Card_id:   20,
	Card_name: "审判",
	Card_type: "MajorArcana",
	Card_up:   "命运好转、复活的喜悦、恢复健康",
	Card_down: "一蹶不振、尚未开始便已结束、自我怀疑、不予理睬",
	Card_file: "MajorArcana/20-JUDGEMENT"}, {
	Card_id:   21,
	Card_name: "世界",
	Card_type: "MajorArcana",
	Card_up:   "愿望达成、获得成功、到达目的地",
	Card_down: "无法投入、不安现状、半途而废、盲目接受",
	Card_file: "MajorArcana/21-THE-WORLD"}, {
	Card_id:   22,
	Card_name: "宝剑ACE",
	Card_type: "Swords",
	Card_up:   "有进取心和攻击性、敏锐、理性、成功的开始",
	Card_down: "易引起争端、逞强而招致灾难、偏激专横、不公正的想法",
	Card_file: "Swords/SWORDS-01"}, {
	Card_id:   23,
	Card_name: "宝剑2",
	Card_type: "Swords",
	Card_up:   "想法的对立、选择的时机、意见不合且暗流汹涌",
	Card_down: "做出选择但流言与欺诈会浮出水面、犹豫不决导致错失机会",
	Card_file: "Swords/SWORDS-02"}, {
	Card_id:   24,
	Card_name: "宝剑3",
	Card_type: "Swords",
	Card_up:   "感情受到伤害、生活中出现麻烦、自怜自哀",
	Card_down: "心理封闭、情绪不安、逃避、伤害周边的人",
	Card_file: "Swords/SWORDS-03"}, {
	Card_id:   25,
	Card_name: "宝剑4",
	Card_type: "Swords",
	Card_up:   "养精蓄锐、以退为进、放缓行动、留意总结",
	Card_down: "即刻行动、投入生活、未充分准备却慌忙应对",
	Card_file: "Swords/SWORDS-04"}, {
	Card_id:   26,
	Card_name: "宝剑5",
	Card_type: "Swords",
	Card_up:   "矛盾冲突、不择手段伤害对方、赢得比赛却失去关系",
	Card_down: "找到应对方法、冲突有解决的可能性、双方愿意放下武器",
	Card_file: "Swords/SWORDS-05"}, {
	Card_id:   27,
	Card_name: "宝剑6",
	Card_type: "Swords",
	Card_up:   "伤口迟迟没能痊愈、现在没有很好的对策、未来存在更多的艰难",
	Card_down: "深陷于困难、鲁莽地解决却忽视背后更大的问题、需要其他人的帮助或救援",
	Card_file: "Swords/SWORDS-06"}, {
	Card_id:   28,
	Card_name: "宝剑7",
	Card_type: "Swords",
	Card_up:   "疏忽大意、有隐藏很深的敌人、泄密、非常手段或小伎俩无法久用",
	Card_down: "意想不到的好运、计划不周全、掩耳盗铃",
	Card_file: "Swords/SWORDS-07"}, {
	Card_id:   29,
	Card_name: "宝剑8",
	Card_type: "Swords",
	Card_up:   "孤立无助、陷入艰难处境、受困于想法导致行动受阻",
	Card_down: "摆脱束缚、脱离危机、重新起步",
	Card_file: "Swords/SWORDS-08"}, {
	Card_id:   30,
	Card_name: "宝剑9",
	Card_type: "Swords",
	Card_up:   "精神上的恐惧、害怕、焦虑、前路不顺的预兆",
	Card_down: "事情出现转机、逐渐摆脱困境、沉溺于过去、正视现实",
	Card_file: "Swords/SWORDS-09"}, {
	Card_id:   31,
	Card_name: "宝剑10",
	Card_type: "Swords",
	Card_up:   "进展严重受阻、无路可走、面临绝境、重新归零的机会",
	Card_down: "绝处逢生、东山再起的希望、物极必反",
	Card_file: "Swords/SWORDS-10"}, {
	Card_id:   32,
	Card_name: "宝剑国王",
	Card_type: "Swords",
	Card_up:   "公正、权威、领导力、冷静",
	Card_down: "思想偏颇、强加观念、极端、不择手段",
	Card_file: "Swords/SWORDS-KING"}, {
	Card_id:   33,
	Card_name: "宝剑王后",
	Card_type: "Swords",
	Card_up:   "理性、思考敏捷、有距离感、公正不阿",
	Card_down: "固执、想法偏激、高傲、盛气凌人",
	Card_file: "Swords/SWORDS-QUEEN"}, {
	Card_id:   34,
	Card_name: "宝剑骑士",
	Card_type: "Swords",
	Card_up:   "勇往直前的行动力、充满激情",
	Card_down: "计划不周、天马行空、缺乏耐心、做事轻率、自负",
	Card_file: "Swords/SWORDS-KNIGHT"}, {
	Card_id:   35,
	Card_name: "宝剑侍从",
	Card_type: "Swords",
	Card_up:   "思维发散、洞察力、谨慎的判断",
	Card_down: "短见、做事虎头蛇尾、对信息不加以过滤分析",
	Card_file: "Swords/SWORDS-PAGE"}, {
	Card_id:   36,
	Card_name: "权杖ACE",
	Card_type: "Wands",
	Card_up:   "新的开端、新的机遇、燃烧的激情、创造力",
	Card_down: "新行动失败的可能性比较大、开端不佳、意志力薄弱",
	Card_file: "Wands/WANDS-01"}, {
	Card_id:   37,
	Card_name: "权杖2",
	Card_type: "Wands",
	Card_up:   "高瞻远瞩、规划未来、在习惯与希望间做选择",
	Card_down: "犹豫不决、行动受阻、花费太多时间在选择上",
	Card_file: "Wands/WANDS-02"}, {
	Card_id:   38,
	Card_name: "权杖3",
	Card_type: "Wands",
	Card_up:   "探索的好时机、身心灵的契合、领导能力、主导地位",
	Card_down: "合作不顺、欠缺领导能力、团队不和谐",
	Card_file: "Wands/WANDS-03"}, {
	Card_id:   39,
	Card_name: "权杖4",
	Card_type: "Wands",
	Card_up:   "和平繁荣、关系稳固、学业或事业发展稳定",
	Card_down: "局势失衡、稳固的基础被打破、人际关系不佳、收成不佳",
	Card_file: "Wands/WANDS-04"}, {
	Card_id:   40,
	Card_name: "权杖5",
	Card_type: "Wands",
	Card_up:   "竞争、冲突、内心的矛盾、缺乏共识",
	Card_down: "不公平的竞争、达成共识",
	Card_file: "Wands/WANDS-05"}, {
	Card_id:   41,
	Card_name: "权杖6",
	Card_type: "Wands",
	Card_up:   "获得胜利、成功得到回报、进展顺利、有望水到渠成",
	Card_down: "短暂的成功、骄傲自满、失去自信",
	Card_file: "Wands/WANDS-06"}, {
	Card_id:   42,
	Card_name: "权杖7",
	Card_type: "Wands",
	Card_up:   "坚定信念、态度坚定、内芯的权衡与决断、相信自己的观点与能力",
	Card_down: "对自己的能力产生怀疑、缺乏自信与动力、缺乏意志力",
	Card_file: "Wands/WANDS-07"}, {
	Card_id:   43,
	Card_name: "权杖8",
	Card_type: "Wands",
	Card_up:   "目标明确、一鼓作气、进展神速、趁热打铁、旅行",
	Card_down: "方向错误、行动不一致、急躁冲动、计划延误",
	Card_file: "Wands/WANDS-08"}, {
	Card_id:   44,
	Card_name: "权杖9",
	Card_type: "Wands",
	Card_up:   "做好准备以应对困难、自我防御、蓄势待发、力量的对立",
	Card_down: "遭遇逆境、失去自信、士气低落",
	Card_file: "Wands/WANDS-09"}, {
	Card_id:   45,
	Card_name: "权杖10",
	Card_type: "Wands",
	Card_up:   "责任感、内芯的热忱、过重的负担、过度劳累",
	Card_down: "难以承受的压力、高估自身的能力、调整自己的步调、逃避责任",
	Card_file: "Wands/WANDS-10"}, {
	Card_id:   46,
	Card_name: "权杖国王",
	Card_type: "Wands",
	Card_up:   "行动力强、态度明确、运筹帷幄、领袖魅力",
	Card_down: "独断专行、严苛、态度傲慢",
	Card_file: "Wands/WANDS-KING"}, {
	Card_id:   47,
	Card_name: "权杖王后",
	Card_type: "Wands",
	Card_up:   "刚柔并济、热情而温和、乐观而活泼",
	Card_down: "情绪化、信心不足、热情消退、孤独",
	Card_file: "Wands/WANDS-QUEEN"}, {
	Card_id:   48,
	Card_name: "权杖骑士",
	Card_type: "Wands",
	Card_up:   "行动力、精力充沛、新的旅程、对现状不满足的改变",
	Card_down: "有勇无谋、鲁莽、行动延迟、计划不周、急躁",
	Card_file: "Wands/WANDS-KNIGHT"}, {
	Card_id:   49,
	Card_name: "权杖侍从",
	Card_type: "Wands",
	Card_up:   "新计划的开始、尝试新事物、好消息传来",
	Card_down: "三分钟热度、规划太久导致进展不顺、坏消息传来",
	Card_file: "Wands/WANDS-PAGE"}, {
	Card_id:   50,
	Card_name: "圣杯ACE",
	Card_type: "Cups",
	Card_up:   "新恋情或新友情、精神愉悦、心灵满足",
	Card_down: "情感缺失、缺乏交流、虚情假意",
	Card_file: "Cups/CUPS-01"}, {
	Card_id:   51,
	Card_name: "圣杯2",
	Card_type: "Cups",
	Card_up:   "和谐对等的关系、情侣间的相互喜爱、合作顺利",
	Card_down: "两性关系趋于极端、情感的割裂、双方不平等、冲突",
	Card_file: "Cups/CUPS-02"}, {
	Card_id:   52,
	Card_name: "圣杯3",
	Card_type: "Cups",
	Card_up:   "达成合作、努力取得成果",
	Card_down: "乐极生悲、无法达成共识、团队不和",
	Card_file: "Cups/CUPS-03"}, {
	Card_id:   53,
	Card_name: "圣杯4",
	Card_type: "Cups",
	Card_up:   "身心俱疲、缺乏动力、对事物缺乏兴趣、情绪低潮",
	Card_down: "新的人际关系、有所行动、脱离低潮期",
	Card_file: "Cups/CUPS-04"}, {
	Card_id:   54,
	Card_name: "圣杯5",
	Card_type: "Cups",
	Card_up:   "过度注意失去的事物、自责、自我怀疑、因孤傲而拒绝外界帮助",
	Card_down: "走出悲伤、破釜沉舟、东山再起",
	Card_file: "Cups/CUPS-05"}, {
	Card_id:   55,
	Card_name: "圣杯6",
	Card_type: "Cups",
	Card_up:   "思乡、美好的回忆、纯真的情感、简单的快乐、安全感",
	Card_down: "沉溺于过去、不美好的回忆、不甘受束缚",
	Card_file: "Cups/CUPS-06"}, {
	Card_id:   56,
	Card_name: "圣杯7",
	Card_type: "Cups",
	Card_up:   "不切实际的幻想、不踏实的人际关系、虚幻的情感、生活混乱",
	Card_down: "看清现实、对物质的不满足、做出明智的选择",
	Card_file: "Cups/CUPS-07"}, {
	Card_id:   57,
	Card_name: "圣杯8",
	Card_type: "Cups",
	Card_up:   "离开熟悉的人事物、不沉醉于目前的成果、经考虑后的行动",
	Card_down: "犹豫不决、失去未来的规划、维持现状",
	Card_file: "Cups/CUPS-08"}, {
	Card_id:   58,
	Card_name: "圣杯9",
	Card_type: "Cups",
	Card_up:   "愿望极有可能实现、满足现状、物质与精神富足",
	Card_down: "物质受损失、不懂节制、寻求更高层次的快乐",
	Card_file: "Cups/CUPS-09"}, {
	Card_id:   59,
	Card_name: "圣杯10",
	Card_type: "Cups",
	Card_up:   "团队和谐、人际关系融洽、家庭和睦",
	Card_down: "团队不和、人际关系不和、冲突",
	Card_file: "Cups/CUPS-10"}, {
	Card_id:   60,
	Card_name: "圣杯国王",
	Card_type: "Cups",
	Card_up:   "创造力、决策力、某方面的专家、有条件的分享或交换",
	Card_down: "表里不一、行为另有所图、对自我创造力的不信任",
	Card_file: "Cups/CUPS-KING"}, {
	Card_id:   61,
	Card_name: "圣杯王后",
	Card_type: "Cups",
	Card_up:   "感情丰富而细腻、重视直觉、感性的思考",
	Card_down: "过度情绪化、用情不专、心灵的孤立",
	Card_file: "Cups/CUPS-QUEEN"}, {
	Card_id:   62,
	Card_name: "圣杯骑士",
	Card_type: "Cups",
	Card_up:   "在等待与行动之间做出决定、新的机会即将到来",
	Card_down: "用情不专、消极的等待、对于情感的行动错误",
	Card_file: "Cups/CUPS-KNIGHT"}, {
	Card_id:   63,
	Card_name: "圣杯侍从",
	Card_type: "Cups",
	Card_up:   "情感的表达与奉献、积极的消息即将传来、情感的追求但不成熟",
	Card_down: "情感的追求但错误、感情暧昧、过度执着于情感或问题",
	Card_file: "Cups/CUPS-PAGE"}, {
	Card_id:   64,
	Card_name: "星币ACE",
	Card_type: "Pentacles",
	Card_up:   "新的机遇、顺利发展、物质回报",
	Card_down: "金钱上的损失、发展不顺、物质丰富但精神虚空",
	Card_file: "Pentacles/PENTACLES-01"}, {
	Card_id:   65,
	Card_name: "星币2",
	Card_type: "Pentacles",
	Card_up:   "收支平衡、财富的流通、生活的波动与平衡",
	Card_down: "用钱过度、难以维持平衡、面临物质的损失",
	Card_file: "Pentacles/PENTACLES-02"}, {
	Card_id:   66,
	Card_name: "星币3",
	Card_type: "Pentacles",
	Card_up:   "团队合作、沟通顺畅、工作熟练、关系稳定",
	Card_down: "分工不明确、人际关系不和、专业技能不足",
	Card_file: "Pentacles/PENTACLES-03"}, {
	Card_id:   67,
	Card_name: "星币4",
	Card_type: "Pentacles",
	Card_up:   "安于现状、吝啬、守财奴、财富停滞、精神匮乏",
	Card_down: "入不敷出、奢侈无度、挥霍",
	Card_file: "Pentacles/PENTACLES-04"}, {
	Card_id:   68,
	Card_name: "星币5",
	Card_type: "Pentacles",
	Card_up:   "经济危机、同甘共苦、艰难时刻",
	Card_down: "居住问题、生活混乱、劳燕分飞",
	Card_file: "Pentacles/PENTACLES-05"}, {
	Card_id:   69,
	Card_name: "星币6",
	Card_type: "Pentacles",
	Card_up:   "慷慨、给予、礼尚往来、财务稳定且乐观",
	Card_down: "自私、暗藏心机、负债或在情义上亏欠于人",
	Card_file: "Pentacles/PENTACLES-06"}, {
	Card_id:   70,
	Card_name: "星币7",
	Card_type: "Pentacles",
	Card_up:   "等待时机成熟、取得阶段性成果、思考计划",
	Card_down: "事倍功半、投资失利、踟蹰不决",
	Card_file: "Pentacles/PENTACLES-07"}, {
	Card_id:   71,
	Card_name: "星币8",
	Card_type: "Pentacles",
	Card_up:   "工作专注、技能娴熟、进取心、做事有条理",
	Card_down: "精力分散、工作乏味、工作产出不佳",
	Card_file: "Pentacles/PENTACLES-08"}, {
	Card_id:   72,
	Card_name: "星币9",
	Card_type: "Pentacles",
	Card_up:   "事业收获、持续为自己创造有利条件、懂得理财储蓄",
	Card_down: "失去财富、舍弃金钱追求生活、管理能力欠缺",
	Card_file: "Pentacles/PENTACLES-09"}, {
	Card_id:   73,
	Card_name: "星币10",
	Card_type: "Pentacles",
	Card_up:   "团队和谐、成功的事业伙伴、家族和谐",
	Card_down: "团队不和、投资合伙暂缓、家庭陷入不和",
	Card_file: "Pentacles/PENTACLES-10"}, {
	Card_id:   74,
	Card_name: "星币国王",
	Card_type: "Pentacles",
	Card_up:   "成功人士、追求物质、善于经营、值得信赖、成熟务实",
	Card_down: "缺乏经济头脑、缺乏信任、管理不善、失去信赖",
	Card_file: "Pentacles/PENTACLES-KING"}, {
	Card_id:   75,
	Card_name: "星币王后",
	Card_type: "Pentacles",
	Card_up:   "成熟、繁荣、值得信赖、温暖、安宁",
	Card_down: "爱慕虚荣、生活浮华、态度恶劣",
	Card_file: "Pentacles/PENTACLES-QUEEN"}, {
	Card_id:   76,
	Card_name: "星币骑士",
	Card_type: "Pentacles",
	Card_up:   "讲究效率、责任感赖、稳重、有计划",
	Card_down: "懈怠、思想保守、发展停滞不前",
	Card_file: "Pentacles/PENTACLES-KNIGHT"}, {
	Card_id:   77,
	Card_name: "星币侍从",
	Card_type: "Pentacles",
	Card_up:   "善于思考和学习、求知欲旺盛、与知识或者研究工作有关的好消息",
	Card_down: "知识贫乏、自我认知不足、金钱上面临损失、视野狭窄",
	Card_file: "Pentacles/PENTACLES-PAGE"},
}
